
import { type Question } from './types';

export const genders = ['回答しない', '男性', '女性', 'その他'];
export const bloodTypes = ['A型', 'B型', 'O型', 'AB型'];
export const zodiacs = ['牡羊座', '牡牛座', '双子座', '蟹座', '獅子座', '乙女座', '天秤座', '蠍座', '射手座', '山羊座', '水瓶座', '魚座'];
export const etoSigns = ['子', '丑', '寅', '卯', '辰', '巳', '午', '未', '申', '酉', '戌', '亥'];
export const mbtiTypes = [
  '不明', 'ISTJ', 'ISFJ', 'INFJ', 'INTJ', 'ISTP', 'ISFP', 'INFP', 'INTP',
  'ESTP', 'ESFP', 'ENFP', 'ENTP', 'ESTJ', 'ESFJ', 'ENFJ', 'ENTJ'
];

export const industries = ['指定なし', 'IT・通信', 'メーカー', '商社', '小売', '飲食業', '金融', '不動産', '建設', 'コンサルティング', '広告・メディア', '医療・福祉', '教育', '人材サービス', 'その他'];

export const mbtiQuestions: Question[] = [
  // EI: 23 questions
  { id: 1, category: 'EI', poleA: { id: 'E', text: '大勢のパーティーが好きだ' }, poleB: { id: 'I', text: '少人数の集まりを好む' } },
  { id: 2, category: 'EI', poleA: { id: 'E', text: '話題の中心にいることが多い' }, poleB: { id: 'I', text: '聞き役になることが多い' } },
  { id: 3, category: 'EI', poleA: { id: 'E', text: '新しい人に会うと元気になる' }, poleB: { id: 'I', text: '新しい人に会うとエネルギーを消耗する' } },
  { id: 4, category: 'EI', poleA: { id: 'E', text: '週末は外出して過ごしたい' }, poleB: { id: 'I', text: '週末は家で静かに過ごしたい' } },
  { id: 5, category: 'EI', poleA: { id: 'E', text: '考えるより先に行動するタイプだ' }, poleB: { id: 'I', text: 'よく考えてから行動するタイプだ' } },
  { id: 6, category: 'EI', poleA: { id: 'E', text: '多くの友人と浅く付き合う' }, poleB: { id: 'I', text: '少数の友人と深く付き合う' } },
  { id: 7, category: 'EI', poleA: { id: 'E', text: '電話で話すのが好きだ' }, poleB: { id: 'I', text: 'テキストメッセージでのやり取りを好む' } },
  { id: 8, category: 'EI', poleA: { id: 'E', text: 'グループ討議で積極的に発言する' }, poleB: { id: 'I', text: 'グループ討議ではまず人の意見を聞く' } },
  { id: 9, category: 'EI', poleA: { id: 'E', text: '自分の考えは話しながらまとめる' }, poleB: { id: 'I', text: '自分の考えは頭の中で整理してから話す' } },
  { id: 10, category: 'EI', poleA: { id: 'E', text: 'スポットライトを浴びることに抵抗がない' }, poleB: { id: 'I', text: '人前に出るのはできるだけ避けたい' } },
  { id: 11, category: 'EI', poleA: { id: 'E', text: '活動的な趣味が多い' }, poleB: { id: 'I', text: '静かで個人的な趣味が多い' } },
  { id: 12, category: 'EI', poleA: { id: 'E', text: '初対面の人ともすぐに打ち解けられる' }, poleB: { id: 'I', text: '人に心を開くのに時間がかかる' } },
  { id: 13, category: 'EI', poleA: { id: 'E', text: '沈黙が気まずく、何か話そうとする' }, poleB: { id: 'I', text: '沈黙は気にならず、自然なことだと思う' } },
  { id: 14, category: 'EI', poleA: { id: 'E', text: '仕事はチームで進めたい' }, poleB: { id: 'I', text: '仕事は一人で集中したい' } },
  { id: 15, category: 'EI', poleA: { id: 'E', text: '賑やかな場所が好きだ' }, poleB: { id: 'I', text: '静かな場所が好きだ' } },
  { id: 16, category: 'EI', poleA: { id: 'E', text: '幅広いトピックについて話したい' }, poleB: { id: 'I', text: '特定のトピックを深く掘り下げたい' } },
  { id: 17, category: 'EI', poleA: { id: 'E', text: '周囲の出来事に常にアンテナを張っている' }, poleB: { id: 'I', text: '自分の内面の世界に集中している' } },
  { id: 18, category: 'EI', poleA: { id: 'E', text: 'すぐに返事をしないと落ち着かない' }, poleB: { id: 'I', text: 'じっくり考えてから返事をしたい' } },
  { id: 19, category: 'EI', poleA: { id: 'E', text: '外向的だと言われることが多い' }, poleB: { id: 'I', text: '内向的だと言われることが多い' } },
  { id: 20, category: 'EI', poleA: { id: 'E', text: 'イベントの主役になることに喜びを感じる' }, poleB: { id: 'I', text: 'イベントを陰で支える役割を好む' } },
  { id: 21, category: 'EI', poleA: { id: 'E', text: '多くのタスクを同時にこなせる' }, poleB: { id: 'I', text: '一つのタスクに集中したい' } },
  { id: 22, category: 'EI', poleA: { id: 'E', text: '他人とエネルギーを分かち合いたい' }, poleB: { id: 'I', text: '自分のエネルギーは内に留めておきたい' } },
  { id: 23, category: 'EI', poleA: { id: 'E', text: '人といると時間が経つのが早い' }, poleB: { id: 'I', text: '一人でいると時間が経つのが早い' } },
  // SN: 23 questions
  { id: 24, category: 'SN', poleA: { id: 'S', text: '現実的で地に足がついている' }, poleB: { id: 'N', text: '想像力豊かで夢見がちだ' } },
  { id: 25, category: 'SN', poleA: { id: 'S', text: '具体的な事実やデータを重視する' }, poleB: { id: 'N', text: '全体的なパターンや関連性を見る' } },
  { id: 26, category: 'SN', poleA: { id: 'S', text: '経験から学ぶことが多い' }, poleB: { id: 'N', text: '理論から学ぶことが多い' } },
  { id: 27, category: 'SN', poleA: { id: 'S', text: '説明書を順番に読む' }, poleB: { id: 'N', text: 'まずは自分で試してから説明書を読む' } },
  { id: 28, category: 'SN', poleA: { id: 'S', text: '「今、ここ」に集中する' }, poleB: { id: 'N', text: '「これからどうなるか」を考える' } },
  { id: 29, category: 'SN', poleA: { id: 'S', text: '実用的なものを好む' }, poleB: { id: 'N', text: '独創的なものを好む' } },
  { id: 30, category: 'SN', poleA: { id: 'S', text: '慣れたやり方を信頼する' }, poleB: { id: 'N', text: '新しいやり方を試したがる' } },
  { id: 31, category: 'SN', poleA: { id: 'S', text: '五感で感じられるものを信じる' }, poleB: { id: 'N', text: '直感やひらめきを信じる' } },
  { id: 32, category: 'SN', poleA: { id: 'S', text: '詳細を覚えるのが得意だ' }, poleB: { id: 'N', text: '大枠を捉えるのが得意だ' } },
  { id: 33, category: 'SN', poleA: { id: 'S', text: '物事をありのままに見る' }, poleB: { id: 'N', text: '物事の裏にある意味を探る' } },
  { id: 34, category: 'SN', poleA: { id: 'S', text: '森よりも木を見るタイプだ' }, poleB: { id: 'N', text: '木よりも森を見るタイプだ' } },
  { id: 35, category: 'SN', poleA: { id: 'S', text: '事実に基づいた会話を好む' }, poleB: { id: 'N', text: '可能性についての会話を好む' } },
  { id: 36, category: 'SN', poleA: { id: 'S', text: '現実的な問題解決が得意だ' }, poleB: { id: 'N', text: '概念的な問題解決が得意だ' } },
  { id: 37, category: 'SN', poleA: { id: 'S', text: '手順通りに進めるのが好きだ' }, poleB: { id: 'N', text: '自由に発想を広げるのが好きだ' } },
  { id: 38, category: 'SN', poleA: { id: 'S', text: '比喩よりも直接的な表現を好む' }, poleB: { id: 'N', text: '比喩や象徴的な表現をよく使う' } },
  { id: 39, category: 'SN', poleA: { id: 'S', text: '過去の実績を重視する' }, poleB: { id: 'N', text: '未来のビジョンを重視する' } },
  { id: 40, category: 'SN', poleA: { id: 'S', text: '観察力が鋭いと言われる' }, poleB: { id: 'N', text: '洞察力が鋭いと言われる' } },
  { id: 41, category: 'SN', poleA: { id: 'S', text: '安定した日常を好む' }, poleB: { id: 'N', text: '変化と刺激のある日常を好む' } },
  { id: 42, category: 'SN', poleA: { id: 'S', text: '物事は白黒はっきりさせたい' }, poleB: { id: 'N', text: '可能性は曖昧なままにしておきたい' } },
  { id: 43, category: 'SN', poleA: { id: 'S', text: '地に足のついたアイデアを出す' }, poleB: { id: 'N', text: '斬新で風変わりなアイデアを出す' } },
  { id: 44, category: 'SN', poleA: { id: 'S', text: '実体験を語るのが好きだ' }, poleB: { id: 'N', text: '想像したことを語るのが好きだ' } },
  { id: 45, category: 'SN', poleA: { id: 'S', text: '映画の筋書きを正確に追う' }, poleB: { id: 'N', text: '映画のテーマやメッセージを考える' } },
  { id: 46, category: 'SN', poleA: { id: 'S', text: '目の前のタスクを着実にこなす' }, poleB: { id: 'N', text: '将来の目標のために行動する' } },
  // TF: 23 questions
  { id: 47, category: 'TF', poleA: { id: 'T', text: '判断基準は客観的な論理だ' }, poleB: { id: 'F', text: '判断基準は個人的な価値観だ' } },
  { id: 48, category: 'TF', poleA: { id: 'T', text: '公平さと正義を何よりも重んじる' }, poleB: { id: 'F', text: '共感と調和を何よりも重んじる' } },
  { id: 49, category: 'TF', poleA: { id: 'T', text: '率直な批判を恐れない' }, poleB: { id: 'F', text: '人を傷つけることを避けたい' } },
  { id: 50, category: 'TF', poleA: { id: 'T', text: '事実（真実）を優先する' }, poleB: { id: 'F', text: '人の感情を優先する' } },
  { id: 51, category: 'TF', poleA: { id: 'T', text: '効率性を重視する' }, poleB: { id: 'F', text: '人間関係を重視する' } },
  { id: 52, category: 'TF', poleA: { id: 'T', text: '問題を分析して解決する' }, poleB: { id: 'F', text: '人々を助けて問題を解決する' } },
  { id: 53, category: 'TF', poleA: { id: 'T', text: '感情に流されず冷静でいられる' }, poleB: { id: 'F', text: '他人の感情に共感しやすい' } },
  { id: 54, category: 'TF', poleA: { id: 'T', text: '「なぜ」そうなるのかを知りたい' }, poleB: { id: 'F', text: '「誰が」それに影響されるかを知りたい' } },
  { id: 55, category: 'TF', poleA: { id: 'T', text: '一貫性と原則を大切にする' }, poleB: { id: 'F', text: '状況に応じた柔軟な対応を大切にする' } },
  { id: 56, category: 'TF', poleA: { id: 'T', text: '良い決断は頭でなされるものだ' }, poleB: { id: 'F', text: '良い決断は心でなされるものだ' } },
  { id: 57, category: 'TF', poleA: { id: 'T', text: 'ビジネスライクな関係を好む' }, poleB: { id: 'F', text: '個人的で温かい関係を好む' } },
  { id: 58, category: 'TF', poleA: { id: 'T', text: '相手の意見の論理的な矛盾を指摘する' }, poleB: { id: 'F', text: '相手の意見に同意できる部分を探す' } },
  { id: 59, category: 'TF', poleA: { id: 'T', text: '目的達成のためなら厳しい判断も厭わない' }, poleB: { id: 'F', text: '皆が納得できる結論を探す' } },
  { id: 60, category: 'TF', poleA: { id: 'T', text: 'システムや仕組みに関心がある' }, poleB: { id: 'F', text: '人間やその成長に関心がある' } },
  { id: 61, category: 'TF', poleA: { id: 'T', text: '褒めるときは具体的な成果を挙げる' }, poleB: { id: 'F', text: '褒めるときは相手の努力や気持ちを汲む' } },
  { id: 62, category: 'TF', poleA: { id: 'T', text: '決断の理由を論理的に説明できる' }, poleB: { id: 'F', text: '決断の理由を感情的に説明する' } },
  { id: 63, category: 'TF', poleA: { id: 'T', text: '他人から冷たいと言われることがある' }, poleB: { id: 'F', text: '他人からお人好しと言われることがある' } },
  { id: 64, category: 'TF', poleA: { id: 'T', text: 'タスク指向で仕事を進める' }, poleB: { id: 'F', text: '人間関係指向で仕事を進める' } },
  { id: 65, category: 'TF', poleA: { id: 'T', text: '普遍的なルールを適用したい' }, poleB: { id: 'F', text: 'ケースバイケースで考えたい' } },
  { id: 66, category: 'TF', poleA: { id: 'T', text: '議論では感情を排して話すべきだ' }, poleB: { id: 'F', text: '議論でも感情の共有は大切だ' } },
  { id: 67, category: 'TF', poleA: { id: 'T', text: '自分の感情をコントロールするのが得意だ' }, poleB: { id: 'F', text: '自分の感情を表現するのが得意だ' } },
  { id: 68, category: 'TF', poleA: { id: 'T', text: '成果で人を評価する' }, poleB: { id: 'F', text: '人柄で人を評価する' } },
  { id: 69, category: 'TF', poleA: { id: 'T', text: '決断は一貫しているべきだ' }, poleB: { id: 'F', text: '状況によって決断は変わってよい' } },
  // JP: 24 questions
  { id: 70, category: 'JP', poleA: { id: 'J', text: '計画を立てて物事を進めたい' }, poleB: { id: 'P', text: '状況に応じて柔軟に対応したい' } },
  { id: 71, category: 'JP', poleA: { id: 'J', text: '締め切りは必ず守る' }, poleB: { id: 'P', text: '締め切り間際で集中力が高まる' } },
  { id: 72, category: 'JP', poleA: { id: 'J', text: '整理整頓された環境が好きだ' }, poleB: { id: 'P', text: '多少散らかっていても気にならない' } },
  { id: 73, category: 'JP', poleA: { id: 'J', text: '結論を急ぎたい' }, poleB: { id: 'P', text: '選択肢はできるだけ残しておきたい' } },
  { id: 74, category: 'JP', poleA: { id: 'J', text: '物事は決まっていると安心する' }, poleB: { id: 'P', text: '自由な選択肢があるとワクワクする' } },
  { id: 75, category: 'JP', poleA: { id: 'J', text: 'スケジュール通りに行動する' }, poleB: { id: 'P', text: 'その時の気分で行動する' } },
  { id: 76, category: 'JP', poleA: { id: 'J', text: '一つのタスクを終えてから次に進む' }, poleB: { id: 'P', text: '複数のタスクを同時に進める' } },
  { id: 77, category: 'JP', poleA: { id: 'J', text: 'リストや計画表を作るのが好きだ' }, poleB: { id: 'P', text: 'リストに縛られるのは窮屈だ' } },
  { id: 78, category: 'JP', poleA: { id: 'J', text: '早めに準備を始める' }, poleB: { id: 'P', text: 'ギリギリまで準備を始めない' } },
  { id: 79, category: 'JP', poleA: { id: 'J', text: '予測可能な生活を好む' }, poleB: { id: 'P', text: '予測不可能な生活を楽しむ' } },
  { id: 80, category: 'JP', poleA: { id: 'J', text: '体系的に物事を整理する' }, poleB: { id: 'P', text: 'アイデアを自由に発散させる' } },
  { id: 81, category: 'JP', poleA: { id: 'J', text: '決断は早い方だ' }, poleB: { id: 'P', text: '決断には時間がかかる方だ' } },
  { id: 82, category: 'JP', poleA: { id: 'J', text: 'ルールや規則は守られるべきだ' }, poleB: { id: 'P', text: 'ルールは状況に応じて曲げてもよい' } },
  { id: 83, category: 'JP', poleA: { id: 'J', text: '「完了」した状態が好きだ' }, poleB: { id: 'P', text: '「進行中」の状態が好きだ' } },
  { id: 84, category: 'JP', poleA: { id: 'J', text: '旅行は事前に予約を済ませたい' }, poleB: { id: 'P', text: '旅行は現地で決めたい' } },
  { id: 85, category: 'JP', poleA: { id: 'J', text: '仕事とプライベートの時間はきっちり分けたい' }, poleB: { id: 'P', text: '仕事とプライベートは混ざっても構わない' } },
  { id: 86, category: 'JP', poleA: { id: 'J', text: '白黒はっきりつけたい' }, poleB: { id: 'P', text: 'グレーゾーンがあっても良い' } },
  { id: 87, category: 'JP', poleA: { id: 'J', text: '整然としたアプローチを好む' }, poleB: { id: 'P', text: '探究的なアプローチを好む' } },
  { id: 88, category: 'JP', poleA: { id: 'J', text: '予定が変更されるとストレスを感じる' }, poleB: { id: 'P', text: '予定の変更は新しい機会だと捉える' } },
  { id: 89, category: 'JP', poleA: { id: 'J', text: '物事をコントロールしたい' }, poleB: { id: 'P', text: '物事の流れに身を任せたい' } },
  { id: 90, category: 'JP', poleA: { id: 'J', text: '秩序と構造を求める' }, poleB: { id: 'P', text: '自由と自発性を求める' } },
  { id: 91, category: 'JP', poleA: { id: 'J', text: 'プレゼントは計画的に選ぶ' }, poleB: { id: 'P', text: 'プレゼントはその場のひらめきで選ぶ' } },
  { id: 92, category: 'JP', poleA: { id: 'J', text: '確定した計画に満足する' }, poleB: { id: 'P', text: '未定の可能性に興奮する' } },
  { id: 93, category: 'JP', poleA: { id: 'J', text: '自分のデスクは常に片付いている' }, poleB: { id: 'P', text: '自分のデスクは創造的なカオス状態だ' } },
];
